 const constants = {
  FETCH_ALL_NEWS:"FETCH_ALL_NEWS",
  ADD_NEWS:"ADD_NEWS",
  FETCH_ALL_BANNERS:"FETCH_ALL_BANNERS",
  FETCH_BLOGS_ALL:"FETCH_BLOGS_ALL",
  FETCH_BLOG:"FETCH_BLOG",
  ADD_ERROR:'ADD_ERROR',
  CLEAR_ERROR:'CLEAR_ERROR',
  ADD_STATUS:"ADD_STATUS",
CLEAR_STATUS:"CLEAR_STATUS"
};


export default constants;
